from typing import Any, Literal

from pydantic import BaseModel, Field


class CallTestRequest(BaseModel):
    provider: Literal["local_webrtc", "livekit", "meta_whatsapp"] = Field(
        ..., description="Provider de voz a utilizar."
    )
    to: str | None = Field(
        default=None,
        description="Numero destino en formato E.164. Obligatorio para provider livekit.",
    )
    initial_message: str | None = Field(
        default="Hola, esta es una prueba tecnica autorizada del agente de voz.",
        description="Mensaje inicial del agente.",
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "provider": "livekit",
                    "to": "+569XXXXXXXX",
                    "initial_message": "Hola, esta es una prueba tecnica autorizada.",
                },
                {
                    "provider": "local_webrtc",
                    "initial_message": "Hola, probemos el agente desde navegador.",
                },
            ]
        }
    }


class CallTestResponse(BaseModel):
    ok: bool = True
    call_session_id: str
    provider: str
    status: str
    room_id: str | None = None
    external_call_id: str | None = None


class CallEndRequest(BaseModel):
    call_session_id: str = Field(..., description="Internal call session UUID to end.")

    model_config = {
        "json_schema_extra": {"example": {"call_session_id": "0d4d2263-0ea7-488a-9261-092a720213b8"}}
    }


class CallEndResponse(BaseModel):
    ok: bool = True
    call_session_id: str
    status: str
    duration_seconds: int | None = None


class CallStatusResponse(BaseModel):
    id: str
    provider: str
    direction: str
    to_number: str | None = None
    status: str
    started_at: str | None = None
    ended_at: str | None = None
    duration_seconds: int | None = None
    summary_json: Any | None = None
    error_message: str | None = None


class DemoSessionRequest(BaseModel):
    initial_message: str | None = Field(
        default="Hola, probemos el agente desde navegador.",
        description="Greeting or first response to steer the demo session.",
    )

    model_config = {
        "json_schema_extra": {
            "example": {"initial_message": "Hola, esta es una prueba tecnica autorizada desde navegador."}
        }
    }


class DemoSessionResponse(BaseModel):
    ok: bool = True
    call_session_id: str
    provider: str
    status: str
    room_id: str | None = None
    realtime: dict[str, Any] | None = None
    connection_mode: str = "server_sdp_proxy"
    warnings: list[str] = Field(default_factory=list)


class DemoEventRequest(BaseModel):
    call_session_id: str = Field(..., description="Internal call session UUID.")
    event_type: str = Field(..., description="Browser-side or Realtime event type.")
    payload: dict[str, Any] = Field(default_factory=dict, description="Event payload.")
    transcript_text: str | None = Field(
        default=None,
        description="Optional transcript text to append to the call session.",
    )
    final: bool = Field(default=False, description="Whether the transcript chunk is final.")


class DemoEventResponse(BaseModel):
    ok: bool = True
    stored: bool = True


class DemoConnectRequest(BaseModel):
    call_session_id: str = Field(..., description="Internal call session UUID.")
    offer_sdp: str = Field(..., description="WebRTC SDP offer generated by the browser.")
    initial_message: str | None = Field(
        default=None,
        description="Optional initial instruction for the first assistant greeting.",
    )


class DemoConnectResponse(BaseModel):
    ok: bool = True
    answer_sdp: str


class CallEventIngestRequest(BaseModel):
    event_type: str = Field(..., description="Application or provider event type.")
    payload: dict[str, Any] = Field(default_factory=dict, description="Event payload.")
    transcript_text: str | None = Field(default=None, description="Optional transcript text to append.")
    final: bool = Field(default=False, description="Whether the transcript chunk is final.")
    status: str | None = Field(default=None, description="Optional updated call status.")


class CallEventIngestResponse(BaseModel):
    ok: bool = True
    stored: bool = True
